# Generated by Django 2.2.25 on 2022-12-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastermind", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guessmodel",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
